"""学习中心配置、来源适配器与任务执行服务。"""

from .book_experience import (
    BOOK_EXPERIENCE_CANDIDATE,
    BOOK_EXPERIENCE_SOURCE,
    BOOK_LORE_CANDIDATE,
    BookExperienceEvidence,
    BookExperienceEvidenceValidator,
    BookExperienceSourceAdapter,
    BookExperienceAdapter,
    EvidenceValidationResult,
    create_book_experience_job,
    register_book_experience_adapter,
    register_book_experience_task,
    validate_book_experience_evidence,
)
from .book_lore import BookLoreSource, BookLoreSourceAdapter, WORLDVIEW_INTERNALIZATION_LABEL
from .domain_promotions import (
    BookExperiencePromotionService,
    BookLorePromotionService,
    FactPromotionService,
    FewShotStylePromotionService,
    RelationshipPromotionService,
    WorldviewInternalizationPromotionService,
    register_default_promotion_targets,
    register_learning_domain_targets,
)
from .candidate_service import CORRECTION_LEARNING_CANDIDATE, LearningCandidateService
from .dedicated_review import (
    DedicatedReviewBridge,
    DedicatedReviewError,
    DedicatedReviewResult,
    DedicatedReviewUnavailable,
)
from .config import (
    LearningBotPolicy,
    LearningConfig,
    diagnose_learning_config,
    resolve_learning_config,
)
from .fewshot_lifecycle import (
    FewShotLifecycleError,
    FewShotReplyCandidateService,
    FewShotUsageFeedbackService,
)
from .job_runner import LearningJobRunResult, LearningJobRunner
from .promotion import (
    DomainPromotionTarget,
    PromotionError,
    PromotionOrchestrator,
    PromotionRegistry,
    PromotionResult,
    PromotionRetryableError,
    PromotionTargetRegistry,
    PromotionTerminalError,
    RetryablePromotionError,
    TargetPromotionRegistry,
    TerminalPromotionError,
)
from .review import LearningReviewError, LearningReviewService
from .source import LearningSourceAdapter, LearningSourceItem, LearningSourceRegistry
from .legacy import (
    BASELINE_COUNTS,
    LEGACY_BOT_ID,
    LEGACY_EVOLUTION_SOURCE,
    LEGACY_EXPERIENCE_SOURCE,
    LEGACY_PENDING_SOURCE,
    LEGACY_PROJECTION_LABELS,
    LegacyMigration,
    LegacyMigrationService,
    migrate_legacy,
    read_legacy_projections,
    run_legacy_migration,
)

__all__ = [
    "BOOK_EXPERIENCE_CANDIDATE",
    "BOOK_EXPERIENCE_SOURCE",
    "BOOK_LORE_CANDIDATE",
    "BookExperienceEvidence",
    "BookExperienceEvidenceValidator",
    "BookExperienceSourceAdapter",
    "BookExperienceAdapter",
    "EvidenceValidationResult",
    "create_book_experience_job",
    "register_book_experience_adapter",
    "register_book_experience_task",
    "validate_book_experience_evidence",
    "BookLoreSource",
    "BookLoreSourceAdapter",
    "WORLDVIEW_INTERNALIZATION_LABEL",
    "BookExperiencePromotionService",
    "BookLorePromotionService",
    "FactPromotionService",
    "FewShotStylePromotionService",
    "RelationshipPromotionService",
    "WorldviewInternalizationPromotionService",
    "register_default_promotion_targets",
    "register_learning_domain_targets",
    "CORRECTION_LEARNING_CANDIDATE",
    "DedicatedReviewBridge",
    "DedicatedReviewError",
    "DedicatedReviewResult",
    "DedicatedReviewUnavailable",
    "LearningBotPolicy",
    "LearningCandidateService",
    "LearningConfig",
    "FewShotLifecycleError",
    "FewShotReplyCandidateService",
    "FewShotUsageFeedbackService",
    "LearningJobRunResult",
    "LearningJobRunner",
    "LearningReviewError",
    "LearningReviewService",
    "DomainPromotionTarget",
    "PromotionError",
    "PromotionOrchestrator",
    "PromotionRegistry",
    "PromotionResult",
    "PromotionRetryableError",
    "PromotionTargetRegistry",
    "PromotionTerminalError",
    "RetryablePromotionError",
    "TargetPromotionRegistry",
    "TerminalPromotionError",
    "LearningSourceAdapter",
    "LearningSourceItem",
    "LearningSourceRegistry",
    "BASELINE_COUNTS",
    "LEGACY_BOT_ID",
    "LEGACY_EVOLUTION_SOURCE",
    "LEGACY_EXPERIENCE_SOURCE",
    "LEGACY_PENDING_SOURCE",
    "LEGACY_PROJECTION_LABELS",
    "LegacyMigration",
    "LegacyMigrationService",
    "migrate_legacy",
    "read_legacy_projections",
    "run_legacy_migration",
    "diagnose_learning_config",
    "resolve_learning_config",
]
